"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Calculation(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class TagsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    NAME_FIELD_NUMBER: _builtins.int
    EXPR_FIELD_NUMBER: _builtins.int
    TAGS_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """The name of this calculated feature."""
    expr: _builtins.str
    """The calculation expression string (SQL-like syntax).
    Supports arithmetic (+, -, *, /), comparisons (>, <, >=, <=, ==, !=),
    logical operators (AND, OR, NOT), and functions (CASE, COALESCE, DATEDIFF).
    """
    @_builtins.property
    def tags(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]:
        """User-defined metadata tags associated with this calculation."""

    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        expr: _builtins.str = ...,
        tags: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["expr", b"expr", "name", b"name", "tags", b"tags"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Calculation: _TypeAlias = Calculation  # noqa: Y015
