# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: feast/core/Calculation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'feast/core/Calculation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x66\x65\x61st/core/Calculation.proto\x12\nfeast.core\"\x87\x01\n\x0b\x43\x61lculation\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x65xpr\x18\x02 \x01(\t\x12/\n\x04tags\x18\x03 \x03(\x0b\x32!.feast.core.Calculation.TagsEntry\x1a+\n\tTagsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42U\n\x10\x66\x65\x61st.proto.coreB\x10\x43\x61lculationProtoZ/github.com/feast-dev/feast/go/protos/feast/coreb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'feast.core.Calculation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020feast.proto.coreB\020CalculationProtoZ/github.com/feast-dev/feast/go/protos/feast/core'
  _globals['_CALCULATION_TAGSENTRY']._loaded_options = None
  _globals['_CALCULATION_TAGSENTRY']._serialized_options = b'8\001'
  _globals['_CALCULATION']._serialized_start=45
  _globals['_CALCULATION']._serialized_end=180
  _globals['_CALCULATION_TAGSENTRY']._serialized_start=137
  _globals['_CALCULATION_TAGSENTRY']._serialized_end=180
# @@protoc_insertion_point(module_scope)
